<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHveQqlE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHveQqlE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHveQqlE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHveQqlE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHveQqlE\App_KernelDevDebugContainer([
    'container.build_hash' => 'HveQqlE',
    'container.build_id' => '3fa5da61',
    'container.build_time' => 1651154096,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHveQqlE');
