<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOoqzend\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOoqzend/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOoqzend.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOoqzend\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOoqzend\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ooqzend',
    'container.build_id' => '8bbfea45',
    'container.build_time' => 1651153623,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOoqzend');
